=== daniizqb/DAM1/Lenguaje de Marcas/Tema 3/Trimestral/ej6.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" attributeFormDefault="unqualified" elementFormDefault="qualified">
<xs:element name="herramientas">
<xs:complexType>
<xs:sequence>
<xs:element name="caja" maxOccurs="unbounded" minOccurs="2">
<xs:complexType>
<xs:sequence>
<xs:element type="xs:string" name="nombre" minOccurs="1"/>
<xs:element name="características">
<xs:complexType>
<xs:sequence>
<xs:choice>
    <xs:element type="xs:string" name="color"/>
    <xs:element type="xs:string" name="peso"/>
</xs:choice>
<xs:element type="xs:date" name="fecha_fab" minOccurs="1"/>
</xs:sequence>
</xs:complexType>
</xs:element>
<xs:element type="xs:byte" name="precio" minOccurs="1"/>
</xs:sequence>
</xs:complexType>
</xs:element>
</xs:sequence>
</xs:complexType>
</xs:element>
</xs:schema>

=== daniizqb/DAM1/Lenguaje de Marcas/Tema 3/Trimestral/herramientas.xml
<?xml version="1.0" encoding="UTF-8"?>
<herramientas xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="ej6.xsd">
   <caja>
      <nombre>martillo</nombre>
      <características>
          <color>rojo</color> 
          <fecha_fab>2010-12-12</fecha_fab>      
      </características>
      <precio>15</precio>
   </caja>
   <caja>
      <nombre>W3C</nombre>
      <características>
          <peso>1 kilo</peso> 
          <fecha_fab>2010-12-12</fecha_fab>           
      </características>
      <precio>13</precio>
   </caja>
</herramientas>
